<a href="https://colab.research.google.com/github/NarekVeranyan05/chicago-data-analysis/blob/main/Data_Analysis_Chicago.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

# 1 Crimes Dataset

Dropped columns:
1. Location
2. Updated On
3. Year
4. X Coordinate
5. Y Coordinate
6. Beat
7. Arrest
8. IUCR

In [ ]:
crime_df = pd.read_csv('/content/sample_data/Crimes_-_2001_to_Present_20260929.csv')
print(len(crime_df))
print(len(crime_df.columns))
crime_df.head()

237497
14

,ID,Case Number,Date,Block,Primary Type,Description,Location Description,Domestic,District,Ward,Community Area,FBI Code,Latitude,Longitude
0,14070711,JJ540599,12/31/2025 09:00:00 PM,038XX W IRVING PARK RD,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,True,17,45.0,16.0,08B,"41,953695743","-87,724418817"
1,14070719,JJ540608,12/31/2025 09:00:00 PM,016XX E 91ST PL,BATTERY,DOMESTIC BATTERY SIMPLE,SIDEWALK,True,4,8.0,48.0,08B,"41,728737511","-87,583801325"
2,14070727,JJ540590,12/31/2025 09:00:00 PM,028XX N NARRAGANSETT AVE,BATTERY,SIMPLE,RESTAURANT,False,25,30.0,19.0,08B,"41,931553962","-87,785708738"
3,14071254,JK100413,12/31/2025 09:00:00 PM,003XX N DEARBORN ST,THEFT,THEFT FROM MOTOR VEHICLE,STREET,False,18,42.0,8.0,06,"41,888131743","-87,629548167"
4,14071261,JK100581,12/31/2025 09:00:00 PM,080XX S MICHIGAN AVE,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE,False,6,6.0,44.0,14,"41,748499094","-87,621312947"

In [ ]:
crime_df.isnull().sum()

ID                         0
Case Number                0
Date                       0
Block                      0
Primary Type               0
Description                0
Location Description    1219
Domestic                   0
District                   0
Ward                       1
Community Area             9
FBI Code                   0
Latitude                1949
Longitude               1949
dtype: int64

In [ ]:
crime_df.isnull().any(axis=1).sum()

np.int64(3112)

# 2 Arrests

No columns dropped

In [ ]:
arrests_df = pd.read_csv('/content/sample_data/Arrests_20260929.csv')

print(len(arrests_df))
print(len(arrests_df.columns))
arrests_df.head()

52686
24

,CHARGE 3 TYPE,CHARGE 3 CLASS,CHARGE 4 STATUTE,CHARGE 4 DESCRIPTION,CHARGE 4 TYPE,CHARGE 4 CLASS,CHARGES STATUTE,CHARGES DESCRIPTION,CHARGES CLASS,CHARGES TYPE,...,CHARGE 2 DESCRIPTION,CHARGE 2 STATUTE,CHARGE 1 CLASS,CHARGE 1 TYPE,CHARGE 1 DESCRIPTION,CHARGE 1 STATUTE,CB_NO,CASE NUMBER,ARREST DATE,RACE
0,NaN,NaN,NaN,NaN,NaN,NaN,720 ILCS 5.0/12-5-A | | |,RECKLESS CONDUCT | | |,A | | |,M | | |,...,NaN,NaN,A,M,RECKLESS CONDUCT,720 ILCS 5.0/12-5-A,30548941,JK133128,01/30/2026 08:13:00 PM,BLACK
1,NaN,NaN,NaN,NaN,NaN,NaN,725 ILCS 5.0/110-3 | | |,ISSUANCE OF WARRANT | | |,Z | | |,| | |,...,NaN,NaN,Z,NaN,ISSUANCE OF WARRANT,725 ILCS 5.0/110-3,30548939,NaN,01/30/2026 08:32:00 PM,BLACK
2,NaN,P,NaN,NaN,NaN,NaN,725 ILCS 5.0/110-3 | 9-64-150(B) | 625 ILCS 5....,ISSUANCE OF WARRANT | PARKING PROHIBITED-STAND...,Z | L | P |,| | |,...,PARKING PROHIBITED-STANDING/PARKING POSTED,9-64-150(B),Z,NaN,ISSUANCE OF WARRANT,725 ILCS 5.0/110-3,30548937,NaN,01/30/2026 08:59:00 PM,BLACK
3,NaN,L,625 ILCS 5.0/6-101,UNLICENSED,NaN,P,625 ILCS 5.0/4-104-A-4 | 625 ILCS 5.0/11-502.1...,POSS TITLE/REGISTRATION NOT AUTHORIZED ON VEHI...,A | A | L | P,M | M | |,...,UNLWFL POSS CANNABIS/DRIVER,625 ILCS 5.0/11-502.15-B,A,M,POSS TITLE/REGISTRATION NOT AUTHORIZED ON VEHICLE,625 ILCS 5.0/4-104-A-4,30548936,JK133148,01/30/2026 08:28:00 PM,WHITE HISPANIC
4,NaN,NaN,NaN,NaN,NaN,NaN,720 ILCS 570.0/402-C | 625 ILCS 5.0/11-502.15-...,PCS - POSSESSION - POSS AMT CON SUB EXCEPT (A)...,4 | A | |,F | M | |,...,UNLWFL POSS CANNABIS/PASS,625 ILCS 5.0/11-502.15-C,4,F,PCS - POSSESSION - POSS AMT CON SUB EXCEPT (A)(D),720 ILCS 570.0/402-C,30548934,JK133107,01/30/2026 07:53:00 PM,BLACK

In [ ]:
arrests_df.isnull().sum()

CHARGE 3 TYPE           46562
CHARGE 3 CLASS          36439
CHARGE 4 STATUTE        43401
CHARGE 4 DESCRIPTION    43401
CHARGE 4 TYPE           50014
CHARGE 4 CLASS          43401
CHARGES STATUTE             0
CHARGES DESCRIPTION         0
CHARGES CLASS               0
CHARGES TYPE                0
CHARGE 3 DESCRIPTION    36439
CHARGE 3 STATUTE        36439
CHARGE 2 CLASS          24922
CHARGE 2 TYPE           36141
CHARGE 2 DESCRIPTION    24922
CHARGE 2 STATUTE        24922
CHARGE 1 CLASS              0
CHARGE 1 TYPE           10477
CHARGE 1 DESCRIPTION        0
CHARGE 1 STATUTE            0
CB_NO                       0
CASE NUMBER             13686
ARREST DATE                 0
RACE                        0
dtype: int64

# 3 Police Stations

Columns dropped:
1. Location
2. X Coordinate
3. Y Coordinate
4. TTY
5. FAX
6. State
7. City

In [ ]:
police_df = pd.read_csv('/content/sample_data/Police_Stations_20260929.csv')
print(len(police_df))
print(len(police_df.columns))
police_df

23
8

,DISTRICT,DISTRICT NAME,ADDRESS,ZIP,PHONE,LATITUDE,LONGITUDE,WEBSITE
0,Headquarters,Headquarters,3510 S Michigan Ave,60653,NaN,"41,83070169","-87,62339535",http://home.chicagopolice.org
1,18,Near North,1160 N Larrabee St,60610,312-742-5870,"41,90324165","-87,64335214",http://home.chicagopolice.org/community/distri...
2,19,Town Hall,850 W Addison St,60613,312-744-8320,"41,94740046","-87,65151202",http://home.chicagopolice.org/community/distri...
3,20,Lincoln,5400 N Lincoln Ave,60625,312-742-8714,"41,97954951","-87,69284451",http://home.chicagopolice.org/community/distri...
4,22,Morgan Park,1900 W Monterey Ave,60643,312-745-0710,"41,69143478","-87,66852039",http://home.chicagopolice.org/community/distri...
5,24,Rogers Park,6464 N Clark St,60626,312-744-5907,"41,99976348","-87,67132429",http://home.chicagopolice.org/community/distri...
6,25,Grand Central,5555 W Grand Ave,60639,312-746-8605,"41,91860889","-87,76557448",http://home.chicagopolice.org/community/distri...
7,1,Central,1718 S State St,60616,312-745-4290,"41,85837259","-87,62735617",http://home.chicagopolice.org/community/distri...
8,2,Wentworth,5101 S Wentworth Ave,60609,312-747-8366,"41,80181109","-87,63056018",http://home.chicagopolice.org/community/distri...
9,3,Grand Crossing,7040 S Cottage Grove Ave,60637,312-747-8201,"41,76643089","-87,60574786",http://home.chicagopolice.org/community/distri...
10,4,South Chicago,2255 E 103rd St,60617,312-747-7581,"41,70793329","-87,56834912",http://home.chicagopolice.org/community/distri...
11,5,Calumet,727 E 111th St,60628,312-747-8210,"41,69272336","-87,60450587",http://home.chicagopolice.org/community/distri...
12,6,Gresham,7808 S Halsted St,60620,312-745-3617,"41,75213684","-87,64422891",http://home.chicagopolice.org/community/distri...
13,7,Englewood,1438 W 63rd St,60636,312-747-8223,"41,77963154","-87,66088702",http://home.chicagopolice.org/community/distri...
14,8,Chicago Lawn,3420 W 63rd St,60629,312-747-8730,"41,77898719","-87,70886382",http://home.chicagopolice.org/community/distri...
15,9,Deering,3120 S Halsted St,60608,312-747-8227,"41,83739443","-87,64640771",http://home.chicagopolice.org/community/distri...
16,10,Ogden,3315 W Ogden Ave,60623,312-747-7511,"41,85668453","-87,70838196",http://home.chicagopolice.org/community/distri...
17,11,Harrison,3151 W Harrison St,60612,312-746-8386,"41,87358229","-87,70548813",http://home.chicagopolice.org/community/distri...
18,12,Near West,1412 S Blue Island Ave\n,60608,312-746-8396,"41,86297662","-87,65697251",http://home.chicagopolice.org/community/distri...
19,14,Shakespeare,2150 N California Ave,60647,312-744-8250,"41,92110332","-87,69745182",http://home.chicagopolice.org/community/distri...
20,15,Austin,5701 W Madison St,60644,312-743-1440,"41,88008346","-87,76819989",http://home.chicagopolice.org/community/distri...
21,16,Jefferson Park,5151 N Milwaukee Ave,60630,312-742-4480,"41,97409445","-87,76614884",http://home.chicagopolice.org/community/distri...
22,17,Albany Park,4650 N Pulaski Rd,60630,312-742-4410,"41,96605342","-87,72811456",http://home.chicagopolice.org/community/distri...

In [ ]:
police_df.isnull().sum()

DISTRICT         0
DISTRICT NAME    0
ADDRESS          0
ZIP              0
PHONE            1
LATITUDE         0
LONGITUDE        0
WEBSITE          0
dtype: int64

# 4 My CHI. My Future. Programs

Columns dropped:
1. Location
2. Image
3. Participants Paid
4. Scholarship Availabke
5. Program Price
6. Contact Phone
7. Contact Email
8. Registration Deadline
9. Registration Open
10. Registration URL
11. Online Address
12. State
13. City
14. End Date

In [ ]:
events_df = pd.read_csv('/content/sample_data/My_CHI._My_Future._Programs_20260929.csv')

print(len(events_df))
print(len(events_df.columns))
events_df.columns

196190
27

/tmp/ipykernel_19912/2470098108.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  events_df = pd.read_csv('/content/sample_data/My_CHI._My_Future._Programs_20260929.csv')

Index(['Program ID', 'Program Name', 'Description', 'Org Name',
       'Category Name', 'Capacity', 'Min Age', 'Max Age', 'Address',
       'ZIP Code', 'Program Type', 'Program URL', 'Start Date', 'End Date',
       'Start Time', 'End Time', 'Contact Name', 'Geographic Cluster Name',
       'Transport Provided', 'Has Free Food', 'Meeting Type',
       'Hidden Programs', 'Featured', 'Tag', 'Latitude', 'Longitude',
       'Custom Categories'],
      dtype='object')

In [ ]:
events_df.isnull().sum()

Program ID                      0
Program Name                    0
Description                     0
Org Name                        0
Category Name                   0
Capacity                    46855
Min Age                         0
Max Age                         0
Address                       880
ZIP Code                     1350
Program Type                    0
Program URL                  5216
Start Date                      0
End Date                   196190
Start Time                  15263
End Time                    15293
Contact Name                14030
Geographic Cluster Name     38123
Transport Provided           3044
Has Free Food                1226
Meeting Type                    0
Hidden Programs                 0
Featured                        0
Tag                             0
Latitude                      870
Longitude                     870
Custom Categories          178376
dtype: int64